/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    profiles: Profile;
    accounts: Account;
    follows: Follow;
    blocks: Block;
    posts: Post;
    stories: Story;
    media: Media;
    comments: Comment;
    reactions: Reaction;
    hashtags: Hashtag;
    likes: Like;
    bookmarks: Bookmark;
    userTags: UserTag;
    conversations: Conversation;
    messages: Message;
    notifications: Notification;
    reports: Report;
    moderationActions: ModerationAction;
    contentFlags: ContentFlag;
    deviceBans: DeviceBan;
    subscriptionTiers: SubscriptionTier;
    subscriptions: Subscription;
    transactions: Transaction;
    settings: Setting;
    featureFlags: FeatureFlag;
    events: Event;
    'event-rsvps': EventRsvp;
    'story-views': StoryView;
    pages: Page;
    categories: Category;
    'legal-pages': LegalPage;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    profiles: ProfilesSelect<false> | ProfilesSelect<true>;
    accounts: AccountsSelect<false> | AccountsSelect<true>;
    follows: FollowsSelect<false> | FollowsSelect<true>;
    blocks: BlocksSelect<false> | BlocksSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    stories: StoriesSelect<false> | StoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    reactions: ReactionsSelect<false> | ReactionsSelect<true>;
    hashtags: HashtagsSelect<false> | HashtagsSelect<true>;
    likes: LikesSelect<false> | LikesSelect<true>;
    bookmarks: BookmarksSelect<false> | BookmarksSelect<true>;
    userTags: UserTagsSelect<false> | UserTagsSelect<true>;
    conversations: ConversationsSelect<false> | ConversationsSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    reports: ReportsSelect<false> | ReportsSelect<true>;
    moderationActions: ModerationActionsSelect<false> | ModerationActionsSelect<true>;
    contentFlags: ContentFlagsSelect<false> | ContentFlagsSelect<true>;
    deviceBans: DeviceBansSelect<false> | DeviceBansSelect<true>;
    subscriptionTiers: SubscriptionTiersSelect<false> | SubscriptionTiersSelect<true>;
    subscriptions: SubscriptionsSelect<false> | SubscriptionsSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
    featureFlags: FeatureFlagsSelect<false> | FeatureFlagsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'event-rsvps': EventRsvpsSelect<false> | EventRsvpsSelect<true>;
    'story-views': StoryViewsSelect<false> | StoryViewsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'legal-pages': LegalPagesSelect<false> | LegalPagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  username: string;
  firstName?: string | null;
  lastName?: string | null;
  userType: 'Organizer' | 'Regular';
  role: 'Super-Admin' | 'Admin' | 'Moderator' | 'Basic';
  avatar?: (number | null) | Media;
  bio?: string | null;
  pronouns?: ('He/Him' | 'She/Her' | 'They/Them' | 'He/They' | 'She/They' | 'Other') | null;
  location?: string | null;
  verified?: boolean | null;
  bannedAt?: string | null;
  lastActiveAt?: string | null;
  followersCount?: number | null;
  followingCount?: number | null;
  postsCount?: number | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  type?: ('image' | 'video' | 'audio') | null;
  owner?: (number | null) | User;
  blurhash?: string | null;
  nsfwScore?: number | null;
  aiTags?:
    | {
        tag?: string | null;
        confidence?: number | null;
        id?: string | null;
      }[]
    | null;
  createdAt: string;
  updatedAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profiles".
 */
export interface Profile {
  id: number;
  user: number | User;
  coverImage?: (number | null) | Media;
  links?:
    | {
        title: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  followerCount?: number | null;
  followingCount?: number | null;
  postCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * OAuth provider accounts linked to users
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts".
 */
export interface Account {
  id: number;
  userId: number | User;
  accountId: string;
  provider: string;
  providerId: string;
  accessToken?: string | null;
  refreshToken?: string | null;
  expiresAt?: string | null;
  scope?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "follows".
 */
export interface Follow {
  id: number;
  follower: number | User;
  following: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blocks".
 */
export interface Block {
  id: number;
  blocker: number | User;
  blocked: number | User;
  reason?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  author?: (number | null) | User;
  /**
   * External user ID from Better Auth
   */
  externalAuthorId?: string | null;
  content?: string | null;
  location?: string | null;
  media?:
    | {
        type?: ('image' | 'video') | null;
        /**
         * External URL for media
         */
        url?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  likesCount?: number | null;
  commentsCount?: number | null;
  repostsCount?: number | null;
  bookmarksCount?: number | null;
  isRepost?: boolean | null;
  originalPost?: (number | null) | Post;
  replyTo?: (number | null) | Post;
  visibility?: ('public' | 'followers' | 'private') | null;
  hashtags?: (number | Hashtag)[] | null;
  editedAt?: string | null;
  moderationStatus?: ('pending' | 'approved' | 'rejected') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hashtags".
 */
export interface Hashtag {
  id: number;
  tag: string;
  usageCount?: number | null;
  blocked?: boolean | null;
  trending?: boolean | null;
  trendingScore?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories".
 */
export interface Story {
  id: number;
  author?: (number | null) | User;
  /**
   * External user ID from Better Auth
   */
  externalAuthorId?: string | null;
  media?: (number | null) | Media;
  items?:
    | {
        type: 'image' | 'video';
        url: string;
        id?: string | null;
      }[]
    | null;
  viewed?: boolean | null;
  caption?: string | null;
  location?: string | null;
  stickers?:
    | {
        type: string;
        data?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  visibility: 'public' | 'followers' | 'private';
  expiresAt: string;
  createdAt: string;
  viewCount?: number | null;
  moderationStatus?: ('pending' | 'approved' | 'rejected') | null;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: number;
  author: number | User;
  post: number | Post;
  content: string;
  likesCount?: number | null;
  /**
   * Only set this when replying to another comment. Comments can only be two levels deep.
   */
  parentComment?: (number | null) | Comment;
  /**
   * Virtual field showing replies to this comment (populated via API).
   */
  replies?: (number | Comment)[] | null;
  createdAt: string;
  moderationStatus?: ('pending' | 'approved' | 'rejected') | null;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reactions".
 */
export interface Reaction {
  id: number;
  user: number | User;
  targetType: 'post' | 'comment' | 'story';
  targetId: string;
  reaction: 'like' | 'love' | 'laugh' | 'angry' | 'sad' | 'wow';
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "likes".
 */
export interface Like {
  id: number;
  user: number | User;
  post?: (number | null) | Post;
  comment?: (number | null) | Comment;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookmarks".
 */
export interface Bookmark {
  id: number;
  user: number | User;
  post: number | Post;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "userTags".
 */
export interface UserTag {
  id: number;
  taggedUser: number | User;
  taggedByUser: number | User;
  media: number | Media;
  x?: number | null;
  y?: number | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations".
 */
export interface Conversation {
  id: number;
  participants: (number | User)[];
  isGroup?: boolean | null;
  groupName?: string | null;
  lastMessageAt?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: number;
  conversation: number | Conversation;
  sender: number | User;
  content: string;
  /**
   * Media attachments (uploaded to CDN)
   */
  media?:
    | {
        type: 'image' | 'video';
        /**
         * CDN URL of the media file
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  mentions?: (number | User)[] | null;
  createdAt: string;
  readAt?: string | null;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  recipient: number | User;
  type: 'follow' | 'like' | 'comment' | 'mention' | 'tag' | 'system';
  actor?: (number | null) | User;
  entityType?: ('post' | 'comment' | 'story' | 'user' | 'message') | null;
  entityId?: string | null;
  createdAt: string;
  readAt?: string | null;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports".
 */
export interface Report {
  id: number;
  reporter: number | User;
  targetType: 'user' | 'post' | 'comment' | 'story' | 'message';
  targetId: string;
  reason: 'spam' | 'harassment' | 'hate_speech' | 'violence' | 'nudity' | 'misinformation' | 'copyright' | 'other';
  description?: string | null;
  status: 'pending' | 'under_review' | 'resolved' | 'dismissed';
  reviewedBy?: (number | null) | User;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "moderationActions".
 */
export interface ModerationAction {
  id: number;
  moderator: number | User;
  action: 'warn' | 'remove' | 'suspend' | 'ban';
  targetType: 'user' | 'post' | 'comment' | 'story' | 'message';
  targetId: string;
  notes?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contentFlags".
 */
export interface ContentFlag {
  id: number;
  contentType: 'post' | 'comment' | 'story' | 'message' | 'media';
  contentId: string;
  flagType: 'nsfw' | 'violence' | 'hate_speech' | 'spam' | 'misinformation';
  confidence?: number | null;
  source: 'ai' | 'user' | 'mod';
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deviceBans".
 */
export interface DeviceBan {
  id: number;
  deviceFingerprint: string;
  user?: (number | null) | User;
  reason?: string | null;
  expiresAt?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptionTiers".
 */
export interface SubscriptionTier {
  id: number;
  creator: number | User;
  name: string;
  price: number;
  currency?: ('usd' | 'eur' | 'gbp') | null;
  perks?:
    | {
        perk: string;
        id?: string | null;
      }[]
    | null;
  active?: boolean | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions".
 */
export interface Subscription {
  id: number;
  subscriber: number | User;
  creator: number | User;
  tier: number | SubscriptionTier;
  status: 'active' | 'cancelled' | 'expired' | 'paused';
  startedAt?: string | null;
  expiresAt?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: number;
  user: number | User;
  amount: number;
  currency: 'usd' | 'eur' | 'gbp';
  provider: 'stripe' | 'paypal' | 'apple_pay' | 'google_pay';
  status: 'pending' | 'completed' | 'failed' | 'refunded';
  externalId?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  key: string;
  value:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "featureFlags".
 */
export interface FeatureFlag {
  id: number;
  flag: string;
  enabled?: boolean | null;
  rolloutPercentage?: number | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  host?: (number | null) | User;
  /**
   * External user ID from Better Auth
   */
  externalAuthorId?: string | null;
  title: string;
  description?: string | null;
  /**
   * Event date (alternative to startDate for mobile app)
   */
  date?: string | null;
  startDate?: string | null;
  endDate?: string | null;
  /**
   * Human-readable time string (e.g., '7:00 PM')
   */
  time?: string | null;
  location?: string | null;
  coverImage?: (number | null) | Media;
  /**
   * External image URL for mobile app
   */
  image?: string | null;
  price?: number | null;
  category?: ('music' | 'sports' | 'art' | 'food' | 'tech' | 'business' | 'health' | 'other') | null;
  likes?: number | null;
  totalAttendees?: number | null;
  isOnline?: boolean | null;
  maxAttendees?: number | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-rsvps".
 */
export interface EventRsvp {
  id: number;
  event: number | Event;
  user: number | User;
  status: 'going' | 'interested' | 'not_going';
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "story-views".
 */
export interface StoryView {
  id: number;
  story: number | Story;
  user: number | User;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout?: (ArchiveBlock | ContentBlock | CallToActionBlock | MediaBlock)[] | null;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          url?: string | null;
          label?: string | null;
          newTab?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          url?: string | null;
          label: string;
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages".
 */
export interface LegalPage {
  id: number;
  slug:
    | 'about'
    | 'privacy-policy'
    | 'terms-of-service'
    | 'community-standards'
    | 'faq'
    | 'eligibility'
    | 'identity-protection'
    | 'ad-policy';
  title: string;
  subtitle?: string | null;
  /**
   * e.g., "January 2026"
   */
  effectiveDate?: string | null;
  /**
   * e.g., "January 2026"
   */
  lastUpdated?: string | null;
  /**
   * Markdown supported. Use ## for headings, • for lists.
   */
  content: string;
  /**
   * Only for FAQ page
   */
  faqs?:
    | {
        /**
         * e.g., General, Verification, Privacy
         */
        category?: string | null;
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'profiles';
        value: number | Profile;
      } | null)
    | ({
        relationTo: 'accounts';
        value: number | Account;
      } | null)
    | ({
        relationTo: 'follows';
        value: number | Follow;
      } | null)
    | ({
        relationTo: 'blocks';
        value: number | Block;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'stories';
        value: number | Story;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'comments';
        value: number | Comment;
      } | null)
    | ({
        relationTo: 'reactions';
        value: number | Reaction;
      } | null)
    | ({
        relationTo: 'hashtags';
        value: number | Hashtag;
      } | null)
    | ({
        relationTo: 'likes';
        value: number | Like;
      } | null)
    | ({
        relationTo: 'bookmarks';
        value: number | Bookmark;
      } | null)
    | ({
        relationTo: 'userTags';
        value: number | UserTag;
      } | null)
    | ({
        relationTo: 'conversations';
        value: number | Conversation;
      } | null)
    | ({
        relationTo: 'messages';
        value: number | Message;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'reports';
        value: number | Report;
      } | null)
    | ({
        relationTo: 'moderationActions';
        value: number | ModerationAction;
      } | null)
    | ({
        relationTo: 'contentFlags';
        value: number | ContentFlag;
      } | null)
    | ({
        relationTo: 'deviceBans';
        value: number | DeviceBan;
      } | null)
    | ({
        relationTo: 'subscriptionTiers';
        value: number | SubscriptionTier;
      } | null)
    | ({
        relationTo: 'subscriptions';
        value: number | Subscription;
      } | null)
    | ({
        relationTo: 'transactions';
        value: number | Transaction;
      } | null)
    | ({
        relationTo: 'settings';
        value: number | Setting;
      } | null)
    | ({
        relationTo: 'featureFlags';
        value: number | FeatureFlag;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'event-rsvps';
        value: number | EventRsvp;
      } | null)
    | ({
        relationTo: 'story-views';
        value: number | StoryView;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'legal-pages';
        value: number | LegalPage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  username?: T;
  firstName?: T;
  lastName?: T;
  userType?: T;
  role?: T;
  avatar?: T;
  bio?: T;
  pronouns?: T;
  location?: T;
  verified?: T;
  bannedAt?: T;
  lastActiveAt?: T;
  followersCount?: T;
  followingCount?: T;
  postsCount?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profiles_select".
 */
export interface ProfilesSelect<T extends boolean = true> {
  user?: T;
  coverImage?: T;
  links?:
    | T
    | {
        title?: T;
        url?: T;
        id?: T;
      };
  followerCount?: T;
  followingCount?: T;
  postCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts_select".
 */
export interface AccountsSelect<T extends boolean = true> {
  userId?: T;
  accountId?: T;
  provider?: T;
  providerId?: T;
  accessToken?: T;
  refreshToken?: T;
  expiresAt?: T;
  scope?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "follows_select".
 */
export interface FollowsSelect<T extends boolean = true> {
  follower?: T;
  following?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blocks_select".
 */
export interface BlocksSelect<T extends boolean = true> {
  blocker?: T;
  blocked?: T;
  reason?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  author?: T;
  externalAuthorId?: T;
  content?: T;
  location?: T;
  media?:
    | T
    | {
        type?: T;
        url?: T;
        image?: T;
        id?: T;
      };
  likesCount?: T;
  commentsCount?: T;
  repostsCount?: T;
  bookmarksCount?: T;
  isRepost?: T;
  originalPost?: T;
  replyTo?: T;
  visibility?: T;
  hashtags?: T;
  editedAt?: T;
  moderationStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories_select".
 */
export interface StoriesSelect<T extends boolean = true> {
  author?: T;
  externalAuthorId?: T;
  media?: T;
  items?:
    | T
    | {
        type?: T;
        url?: T;
        id?: T;
      };
  viewed?: T;
  caption?: T;
  location?: T;
  stickers?:
    | T
    | {
        type?: T;
        data?: T;
        id?: T;
      };
  visibility?: T;
  expiresAt?: T;
  createdAt?: T;
  viewCount?: T;
  moderationStatus?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  type?: T;
  owner?: T;
  blurhash?: T;
  nsfwScore?: T;
  aiTags?:
    | T
    | {
        tag?: T;
        confidence?: T;
        id?: T;
      };
  createdAt?: T;
  updatedAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  author?: T;
  post?: T;
  content?: T;
  likesCount?: T;
  parentComment?: T;
  replies?: T;
  createdAt?: T;
  moderationStatus?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reactions_select".
 */
export interface ReactionsSelect<T extends boolean = true> {
  user?: T;
  targetType?: T;
  targetId?: T;
  reaction?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hashtags_select".
 */
export interface HashtagsSelect<T extends boolean = true> {
  tag?: T;
  usageCount?: T;
  blocked?: T;
  trending?: T;
  trendingScore?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "likes_select".
 */
export interface LikesSelect<T extends boolean = true> {
  user?: T;
  post?: T;
  comment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookmarks_select".
 */
export interface BookmarksSelect<T extends boolean = true> {
  user?: T;
  post?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "userTags_select".
 */
export interface UserTagsSelect<T extends boolean = true> {
  taggedUser?: T;
  taggedByUser?: T;
  media?: T;
  x?: T;
  y?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations_select".
 */
export interface ConversationsSelect<T extends boolean = true> {
  participants?: T;
  isGroup?: T;
  groupName?: T;
  lastMessageAt?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  conversation?: T;
  sender?: T;
  content?: T;
  media?:
    | T
    | {
        type?: T;
        url?: T;
        id?: T;
      };
  mentions?: T;
  createdAt?: T;
  readAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  recipient?: T;
  type?: T;
  actor?: T;
  entityType?: T;
  entityId?: T;
  createdAt?: T;
  readAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reports_select".
 */
export interface ReportsSelect<T extends boolean = true> {
  reporter?: T;
  targetType?: T;
  targetId?: T;
  reason?: T;
  description?: T;
  status?: T;
  reviewedBy?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "moderationActions_select".
 */
export interface ModerationActionsSelect<T extends boolean = true> {
  moderator?: T;
  action?: T;
  targetType?: T;
  targetId?: T;
  notes?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contentFlags_select".
 */
export interface ContentFlagsSelect<T extends boolean = true> {
  contentType?: T;
  contentId?: T;
  flagType?: T;
  confidence?: T;
  source?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deviceBans_select".
 */
export interface DeviceBansSelect<T extends boolean = true> {
  deviceFingerprint?: T;
  user?: T;
  reason?: T;
  expiresAt?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptionTiers_select".
 */
export interface SubscriptionTiersSelect<T extends boolean = true> {
  creator?: T;
  name?: T;
  price?: T;
  currency?: T;
  perks?:
    | T
    | {
        perk?: T;
        id?: T;
      };
  active?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions_select".
 */
export interface SubscriptionsSelect<T extends boolean = true> {
  subscriber?: T;
  creator?: T;
  tier?: T;
  status?: T;
  startedAt?: T;
  expiresAt?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  user?: T;
  amount?: T;
  currency?: T;
  provider?: T;
  status?: T;
  externalId?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  key?: T;
  value?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "featureFlags_select".
 */
export interface FeatureFlagsSelect<T extends boolean = true> {
  flag?: T;
  enabled?: T;
  rolloutPercentage?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  host?: T;
  externalAuthorId?: T;
  title?: T;
  description?: T;
  date?: T;
  startDate?: T;
  endDate?: T;
  time?: T;
  location?: T;
  coverImage?: T;
  image?: T;
  price?: T;
  category?: T;
  likes?: T;
  totalAttendees?: T;
  isOnline?: T;
  maxAttendees?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-rsvps_select".
 */
export interface EventRsvpsSelect<T extends boolean = true> {
  event?: T;
  user?: T;
  status?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "story-views_select".
 */
export interface StoryViewsSelect<T extends boolean = true> {
  story?: T;
  user?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        archive?: T | ArchiveBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              url?: T;
              label?: T;
              newTab?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  caption?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  subtitle?: T;
  effectiveDate?: T;
  lastUpdated?: T;
  content?: T;
  faqs?:
    | T
    | {
        category?: T;
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}